name: plant_disease_detector
description: A reusable plant disease detection widget using TensorFlow Lite for Flutter applications.
version: 1.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: ^0.10.1
  image_picker: ^1.2.0
  tflite_v2: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/model.tflite
    - assets/classes.txt
