name: ai_chatbot
description: A reusable AI chatbot widget using Google Dialogflow for Flutter applications.
version: 1.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dialog_flowtter: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/dialog_flow_auth.json
